### ISSUE TITLE
Repeatable read 에서 읽은 row에 대한 삭제가 가능한가요?

### ISSUE THREAD

**Issue by shouwn** [bghgu/Answer#1]
[Phantom Read](https://github.com/bghgu/Answer#phantom-read) 에서
> 트랜잭션1이 A테이블에서 SELECT한 이후 트랜잭션2에서 A테이블에 내용을 추가/삭제 하는 상황 가정

라고 적혀 있는데요.

shared lock의 경우 다른 트랜젝션에서 shared lock을 걸 수 있지만 exclusive lock을 못 거는 레벨로 알고 있는데요. row 삭제의 경우 exclusive lock을 걸려고 시도합니다.

mysql의 경우 Repeatable read isolation level에서는 SELECT 한 row에 대해서 row level shared lock을 걸기 때문에 삭제가 불가능 한 걸로 알고 있습니다.

**Comment by bghgu** [comment]
해당 부분 다시 수정하겠습니다.
